Bugfix/accumulating token usage
jxnl/instructor pull request #763
Opened 2024-06-15 10:26 UTC by ionflow

In addition to now accumulating tokens for LiteLLM client calls, this fixes a couple issues that I discovered implementing this fix. 

Issue: https://github.com/jxnl/instructor/issues/715

1. InstructorRetryExceptions were not being thrown from retry.py. Now you can capture these exceptions and do something with total_usage data (e.g. calculate the cost of all failed completions)
2. InstructorRetryExceptions had `total_usage` as an `int` type and would never be able to accept `total_usage`. Now it accepts `Usage` (from anthropic.types) and `CompletionUsage` (used by both OpenAI and LiteLLM.

2024-06-16 19:09 UTC, jxnl commented on instructor/utils.py
> +    if isinstance(response_usage, (CompletionUsage, LiteLLMUsage)) and isinstance(
this will make litellm a dependaence, is there a prototype or inferface we can use isntead

2024-06-16 22:38 UTC, jxnl commented on instructor/exceptions.py
> +from anthropic.types import Usage
this will break imports for those who did not instal anthropic

2024-06-25 21:18 UTC, ionflow commented
@jxnl i'm finally getting back to this. any guidance on where I should define these types? we already have a dependency on openai types for CompletionUsage, but if we don't want any more dependencies then we'll need usage types for [Anthropic](https://docs.anthropic.com/en/api/messages), [Google](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/get-token-count) and [Cohere](https://docs.cohere.com/docs/chat-api#response-structure) to support the different structures.

2024-06-30 04:01 UTC, ionflow commented
@jxnl after some more explorations and thinking about how I would want this to work for retries I've come up with a `UnifiedUsage` class and this additional `create_with_completion` argument `with_usage` to support backwards compatibility. Basically we need some universal way to track usage during retries. This unified usage class allows us to support different usage reporting structures.

Please let me know what you think about this approach. I don't want to overcomplicate it, but couldn't think of a more simple way to move forward with full support of all clients.

If you like this I will add tests and address any other feedback you might have.

2024-06-30 18:36 UTC, jxnl commented on instructor/usage.py
> +def convert_to_unified_usage(usage: Any) -> UnifiedUsage:
this is great!

2024-06-30 18:37 UTC, jxnl commented
happy with this! can you just make sure to update the docs for patch and for usage?

2024-07-01 01:50 UTC, ionflow commented
@jxnl I think this is ready.

2024-07-03 02:05 UTC, jxnl approved these changes

2024-07-03 02:19 UTC, jxnl requested changes
it looks like the types are not correct overloaded 

<img width="615" alt="Screenshot 2024-07-02 at 10 18 55 PM" src="https://github.com/jxnl/instructor/assets/4852235/460160b8-cdf2-45c2-aaba-b66e5903e67c">
<img width="617" alt="Screenshot 2024-07-02 at 10 18 48 PM" src="https://github.com/jxnl/instructor/assets/4852235/51990858-d1a4-4dfb-a531-9593d0222adc">

I can take a stab but look at the `from_openai` to see how overload can be used

2024-08-30 15:33 UTC, matt-bernstein commented
Hi, is this PR still in a mergeable state? I need this fix as well and would take a shot at getting it merged if the codebase hasn't diverged too far.

2024-08-31 02:07 UTC, ivanleomk commented
@matt-bernstein I haven't taken a look at this for a while sorry, had a whole bunch of other issues to fix. What is the specific use case you're looking for the accumulating of token usage?

2024-10-04 22:12 UTC, closed without merging